### ISSUE TITLE
nomad.GetPlugin cannot be used in pulumi.DependsOn

### ISSUE THREAD

**Issue by Emil9999** [pulumi/pulumi-nomad#71]
### What happened?

Trying to replicate [this](https://www.pulumi.com/registry/packages/nomad/api-docs/volume/) part of the documentation in golang, specifcally trying to use the output from nomad.getPlugin in a pulumi.DependsOn.

Failing with the following error: `cannot use plugin (variable of type *nomad.GetPluginResult) as type pulumi.Resource in array or slice literal:
        *nomad.GetPluginResult does not implement pulumi.Resource (missing URN method)`

Also tried using GetPluginOutput with similar results. 

### Expected Behavior

Compile.

### Steps to reproduce

Simply use the same code from the documentation provided above.

### Output of `pulumi about`

CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.52.0
gcp     5.26.0
go      unknown
nomad   0.4.1
random  4.13.0

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.19.3 linux/amd64'

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-gcp/sdk/v6  6.52.0
github.com/pulumi/pulumi/sdk/v3      3.68.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @Emil9999 , thanks for pointing out this incorrect docs example. `dependsOn` currently does not support the result of anything other than `pulumi.Resource` - as a workaround, here is the above example rewritten to use an `Apply`, which will ensure that the volume instance is instantiated after the plugin is loaded correctly:
package main

```
import (
    "github.com/pulumi/pulumi-nomad/sdk/go/nomad"
    "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
    pulumi.Run(func(ctx *pulumi.Context) error {
        ebs, err := nomad.GetPlugin(ctx, &nomad.GetPluginArgs{
            PluginId:       "aws-ebs0",
            WaitForHealthy: pulumi.BoolRef(true),
        }, nil)
        if err != nil {
            return err
        }

        _, err = ebs.ID().ApplyT(func(pluginID string) (interface{}, error) {
            volume, err := nomad.NewVolume(ctx, "mysqlVolume", &nomad.VolumeArgs{
                Type:       pulumi.String("csi"),
                PluginId:   pulumi.String(pluginID), // Use the ID of the plugin as an argument
                VolumeId:   pulumi.String("mysql_volume"),
                ExternalId: pulumi.Any(module.Hashistack.Ebs_test_volume_id),
                Capabilities: nomad.VolumeCapabilityArray{
                    &nomad.VolumeCapabilityArgs{
                        AccessMode:     pulumi.String("single-node-writer"),
                        AttachmentMode: pulumi.String("file-system"),
                    },
                },
                MountOptions: &nomad.VolumeMountOptionsArgs{
                    FsType: pulumi.String("ext4"),
                },
                TopologyRequest: &nomad.VolumeTopologyRequest,
            })
            return volume, err
        }).ToVolumeOutput()
        return err
    })
}

```
Please let us know if this helps!

**Comment by Emil9999** [comment]
Thanks for the swift response @aq17.

The way you suggested yields this error for me:
`ebs.ID undefined (type *nomad.GetPluginResult has no field or method ID)`
I couldn't get ApplyT to work on any other GetPluginResult fields, however I used GetPluginOutput to achieve what I need, please let me know if there is something wrong with this approach:

```

import (
    "github.com/pulumi/pulumi-nomad/sdk/go/nomad"
    "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
    pulumi.Run(func(ctx *pulumi.Context) error {

            csiPlugin:= nomad.GetPluginOutput(ctx, nomad.GetPluginOutputArgs{
			            PluginId:       pulumi.String("gcepd"),
			            WaitForHealthy: pulumi.Bool(true),
		            }, nil)
    
    
            _ = csiPlugin.Id().ApplyT(func(id string) (interface{}, error) {
	            volume, err := nomad.NewVolume(ctx, "volume", &nomad.VolumeArgs{
		            Type:       pulumi.String("csi"),
		            PluginId:  pulumi.String("gcep"),
		            Capabilities: nomad.VolumeCapabilityArray{
			            &nomad.VolumeCapabilityArgs{
				            AccessMode:     pulumi.String("single-node-writer"),
				            AttachmentMode: pulumi.String("file-system"),
			            },
		            },
		            MountOptions: &nomad.VolumeMountOptionsArgs{
			            FsType: pulumi.String("ext4"),
		            },
            })
		        if err != nil {
			        return nil, err
		        }
		        return volume, err
	})
 }
}

```

**Comment by aq17** [comment]
@Emil9999 that looks good! Yup, I meant to use GetPluginOutput - Apply can only be applied to an Input or Output.
